# Site settings
title: Jesper Nordenberg
email: Jn222yq@student.lnu.se
description: This is my awesome description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "Notaturtle.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  Noraturtle

# Build settings
markdown: kramdown
